### ISSUE TITLE
Still encoding issues

### ISSUE THREAD

**Issue by crondaemon** [raykrueger/ruby-smpp#21]
Today I experienced my code broken, without any explanation. 
With the very same code as before, code stopped with

```
incompatible character encodings: ASCII-8BIT and US-ASCII at /usr/local/rvm/gems/ruby-1.9.3-p194/bundler/gems/ruby-smpp-dfc81b559bdd/lib/smpp/pdu/base.rb
```

After digging a bit, the only way I found to make it work was

```
@data = fixed_int(length) + fixed_int(command_id) + fixed_int(command_status) + fixed_int(seq)
@data = @data.force_encoding("US-ASCII") + body
```

That's a bad way to solve the problem. Any idea about how patch the calling code? Any idea about how to solve definitively the encoding issues?
Thanks.

**Comment by raykrueger** [comment]
Merge master into the 1.9 branch and try that maybe?

**Comment by renenw** [comment]
i can confirm that the proposed adjustment:

```
@data = fixed_int(length) + fixed_int(command_id) + fixed_int(command_status) + fixed_int(seq)
@data = @data.force_encoding("US-ASCII") + body
```

addresses at least some substantive problems (running on ruby 2.3.1).

Is this project active enough to warrant a merge request?
