### ISSUE TITLE
anjlab or rubymspp

### ISSUE THREAD

**Issue by pepesenaris** [raykrueger/ruby-smpp#26]
Hello

I'm looking for the must up to date version of the ruby-smpp gem. I have found another gem called anjlab-ruby-smpp (https://rubygems.org/gems/anjlab-ruby-smpp).
Does anyone knows if this one still has the problems reported here, ie, all those issues that haven't  been merge in the master branch of the original from raykrueger

**Comment by raykrueger** [comment]
That appears to be some random fork. There's no telling what it's status is. I'd welcome commits to bring ruby-smpp up-to-date. Currently it's stuck on Ruby 1.8.7 is the main problem.

**Comment by raykrueger** [comment]
Also, please use the mailing list for questions.
