### ISSUE TITLE
Moving repo to organization

### ISSUE THREAD

**Issue by crondaemon** [raykrueger/ruby-smpp#27]
Hi @raykrueger 
This project is wonderful but seems to be abandoned... I'm not working anymore on smpp and seems the same for you. So why don't you put it into an organization repo and take on board some developer that actively work on it? To have an active and collaborative community could solve the lack of time/manpower on it. 

Again, it's a good project and it would be a pity to leave it rusting...

**Comment by raykrueger** [comment]
I don't think moving it to an org is gonna bring in a developer to maintain it :)

**Comment by crondaemon** [comment]
May be. But the risk now is that it stales...
